# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_T2BCE_DMA) += t2bce_dma/
obj-$(CONFIG_T2BCE_CORE) += t2bce_core/
obj-$(CONFIG_T2BCE_VHCI) += t2bce_vhci/
obj-$(CONFIG_T2BCE_AUDIO) += t2bce_audio/
